# Generated by Django 2.2.4 on 2019-11-04 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deputy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rada_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('laws', models.IntegerField()),
                ('photo', models.URLField()),
                ('monitoring', models.IntegerField()),
                ('poseshenie', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_month_position', models.IntegerField()),
                ('position_current', models.IntegerField()),
                ('rating_upfoundation', models.IntegerField()),
                ('txt_for_page', models.TextField(max_length=2500)),
            ],
        ),
    ]
