# Generated by Django 2.2.7 on 2019-11-04 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20191104_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deputy',
            old_name='poseshenie',
            new_name='attendance',
        ),
    ]
