# Generated by Django 2.2.7 on 2019-11-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20191104_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='deputy',
            name='party',
            field=models.CharField(choices=[('SN', 'Слуга Народу'), ('OP', 'ОПОЗИЦІЙНА ПЛАТФОРМА - ЗА ЖИТТЯ'), ('BT', 'Батьківщина'), ('ES', 'Європейська Солідарність'), ('HL', 'Голос'), ('ZM', 'За майбутнє'), ('BP', 'Позафракцйні')], default='BP', max_length=200),
        ),
    ]
