# Generated by Django 2.2.7 on 2019-11-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_deputy_party'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deputy',
            old_name='laws',
            new_name='submitted_laws',
        ),
        migrations.AlterField(
            model_name='deputy',
            name='party',
            field=models.CharField(choices=[('SN', 'Слуга Народу'), ('OP', 'ОПОЗИЦІЙНА ПЛАТФОРМА - ЗА ЖИТТЯ'), ('BT', 'Батьківщина'), ('ES', 'Європейська Солідарність'), ('HL', 'Голос'), ('ZM', 'За майбутнє'), ('BP', 'Позафракційні')], default='BP', max_length=200),
        ),
    ]
