# Generated by Django 2.2.4 on 2019-11-08 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0007_auto_20191108_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='deputy',
            name='votes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
