# Generated by Django 2.2.4 on 2019-11-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0008_deputy_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deputy',
            name='votes',
        ),
    ]
