# Generated by Django 2.2.4 on 2019-11-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0009_remove_deputy_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputy',
            name='party',
            field=models.CharField(choices=[('SN', 'Слуга Народу'), ('OP', 'ОПЗЖ'), ('BT', 'Батьківщина'), ('ES', 'ЄС'), ('HL', 'Голос'), ('ZM', 'За майбутнє'), ('BP', 'Позафракційні')], default='BP', max_length=200),
        ),
        migrations.AlterField(
            model_name='uniqueuser',
            name='ip',
            field=models.GenericIPAddressField(default='empty', unpack_ipv4=True),
            preserve_default=False,
        ),
    ]
