# Generated by Django 2.2.4 on 2019-11-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0010_auto_20191109_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='deputy',
            name='name_ukr',
            field=models.CharField(default='Немає', max_length=200),
            preserve_default=False,
        ),
    ]
